"""
project_scaffold.py  —  Phase 4a: Project Scaffolding Tool

Provides the `scaffold_project` tool.  Before any code is written for a
multi-file software project, the agent calls this tool to produce a complete
architecture plan: directory structure, file purposes, dependency ordering,
entry point, test command, and implementation notes.

The scaffold is generated by the local LLM (qwen2.5:14b via Ollama) so it
costs no Claude API tokens and returns quickly.  The resulting JSON is saved
to outputs/{name}/scaffold.json so the agent can reference it throughout the
subsequent implementation phase without re-sending the full plan every turn.

This tool is intentionally NON-DESTRUCTIVE: it only writes a JSON file to
the outputs/ directory (internal bookkeeping), never user source files.
"""

from __future__ import annotations

import json
import logging
import re
from datetime import datetime
from pathlib import Path

from agent_tools import register_tool
from agent_tools.local_llm import local_llm_call

logger = logging.getLogger(__name__)

# Project root — two levels up from this file (backend/agent_tools/ → project root)
_PROJECT_ROOT = Path(__file__).parent.parent.parent
_OUTPUTS_DIR  = _PROJECT_ROOT / "outputs"
_PROFILE_PATH = _PROJECT_ROOT / "memory" / "user_profile.json"

# Supported project type descriptors (informational — passed to the LLM)
_VALID_TYPES = {"python", "web", "cli", "library", "api"}


# ---------------------------------------------------------------------------
# Tool implementation
# ---------------------------------------------------------------------------

async def scaffold_project(
    name: str,
    description: str,
    project_type: str = "python",
) -> dict:
    """
    Generate a complete project specification before any code is written.

    This tool does NOT write source files — it returns a structured plan for
    the agent to follow during subsequent implementation steps.

    Args:
        name:         Short identifier for the project (used as directory name,
                      e.g. "todo_cli", "weather_api").
        description:  One-sentence description of what the project should do.
        project_type: One of "python", "web", "cli", "library", "api".
                      Defaults to "python".

    Returns:
        dict with keys:
          success           — bool
          scaffold          — the parsed scaffold dict (on success)
          saved_to          — path where scaffold.json was written
          file_count        — number of files in the plan
          instruction       — guidance for the agent's next steps
          error             — error message (on failure only)
    """
    # ── Normalise inputs ──────────────────────────────────────────────────────
    name        = name.strip().replace(" ", "_")
    description = description.strip()
    project_type = project_type.strip().lower()

    if project_type not in _VALID_TYPES:
        logger.warning(
            f"[scaffold] Unknown project_type {project_type!r} — defaulting to 'python'."
        )
        project_type = "python"

    # ── Optional user profile context ────────────────────────────────────────
    # If a user profile exists we include a brief summary so the LLM can
    # tailor technology choices to the developer's known preferences.
    profile_context = ""
    try:
        if _PROFILE_PATH.exists():
            with open(_PROFILE_PATH, encoding="utf-8") as f:
                profile = json.load(f)
            # Include only the most relevant keys to keep the prompt compact
            tech = profile.get("tech_stack", {})
            prefs = profile.get("preferences", {})
            if tech or prefs:
                profile_context = (
                    f"\nDeveloper context: {json.dumps({**tech, **prefs}, ensure_ascii=False)[:400]}"
                )
    except Exception as e:
        logger.debug(f"[scaffold] Could not read user profile (non-fatal): {e}")

    # ── Build prompt ──────────────────────────────────────────────────────────
    prompt = (
        f"Generate a complete project scaffold for: {description}\n"
        f"Project name: {name}\n"
        f"Project type: {project_type}{profile_context}\n\n"
        "Return ONLY a JSON object with this exact structure (no explanation, "
        "no markdown fences, just raw JSON):\n"
        "{\n"
        '  "name": "project_name",\n'
        '  "description": "one sentence",\n'
        '  "structure": [\n'
        '    {"path": "relative/path/file.py", "purpose": "what this file does", '
        '"depends_on": ["other/file.py"]}\n'
        "  ],\n"
        '  "entry_point": "main.py or equivalent",\n'
        '  "test_command": "python main.py or pytest etc",\n'
        '  "dependencies": ["package1", "package2"],\n'
        '  "implementation_order": ["file1.py", "file2.py"],\n'
        '  "notes": "anything important about the architecture"\n'
        "}"
    )

    # ── Call local LLM ────────────────────────────────────────────────────────
    logger.info(f"[scaffold] Generating scaffold for project '{name}' ({project_type})…")
    raw_response = await local_llm_call(prompt)

    # ── Parse JSON — strip markdown fences if present ────────────────────────
    scaffold: dict | None = None
    parse_error: str = ""

    # Remove ```json ... ``` or ``` ... ``` wrappers that some models include
    cleaned = re.sub(r"^```(?:json)?\s*", "", raw_response.strip(), flags=re.IGNORECASE)
    cleaned = re.sub(r"\s*```$", "", cleaned)

    # Try to extract the first JSON object if there's extra text around it
    # (some models prepend "Here is the scaffold:" etc.)
    json_match = re.search(r"\{.*\}", cleaned, re.DOTALL)
    if json_match:
        cleaned = json_match.group(0)

    try:
        scaffold = json.loads(cleaned)
    except json.JSONDecodeError as e:
        parse_error = str(e)
        logger.warning(
            f"[scaffold] JSON parse failed for project '{name}': {e}\n"
            f"Raw response (first 400 chars): {raw_response[:400]}"
        )

    if scaffold is None:
        return {
            "success": False,
            "error":   "Failed to generate scaffold. Try a more specific description.",
        }

    # ── Ensure required keys exist ────────────────────────────────────────────
    # Fill in sensible defaults if the LLM omitted optional fields
    scaffold.setdefault("name",                 name)
    scaffold.setdefault("description",          description)
    scaffold.setdefault("structure",            [])
    scaffold.setdefault("entry_point",          "main.py")
    scaffold.setdefault("test_command",         "python main.py")
    scaffold.setdefault("dependencies",         [])
    scaffold.setdefault("implementation_order", [])
    scaffold.setdefault("notes",                "")
    # Phase 5a — set to the repo's full_name (e.g. "username/project") after
    # the agent pushes the project to GitHub; null means not yet pushed.
    scaffold.setdefault("github_repo",          None)

    structure: list = scaffold.get("structure", [])
    file_count = len(structure)

    # ── Save scaffold.json to outputs/{name}/ ─────────────────────────────────
    project_out_dir = _OUTPUTS_DIR / name
    project_out_dir.mkdir(parents=True, exist_ok=True)
    scaffold_path = project_out_dir / "scaffold.json"

    try:
        with open(scaffold_path, "w", encoding="utf-8") as f:
            json.dump(scaffold, f, ensure_ascii=False, indent=2)
        saved_to = f"outputs/{name}/scaffold.json"
        logger.info(
            f"[scaffold] Scaffold saved: {saved_to} "
            f"({file_count} files, entry={scaffold['entry_point']!r})"
        )

        # ── Create initial progress.json if it doesn't exist yet ─────────────
        # project_manager.py reads this file to track which files are done.
        # Creating it here (at scaffold time) ensures the file always exists
        # before the agent starts calling get_project_status / mark_file_complete.
        progress_path = project_out_dir / "progress.json"
        if not progress_path.exists():
            initial_progress = {
                "project_name":    name,
                "created_at":      datetime.utcnow().isoformat(),
                "completed_files": [],
                "last_test":       None,
                "test_attempts":   0,
                "test_history":    [],
            }
            with open(progress_path, "w", encoding="utf-8") as f:
                json.dump(initial_progress, f, indent=2)
            logger.info(f"[scaffold] Initial progress.json created for '{name}'.")
    except Exception as e:
        logger.error(f"[scaffold] Could not save scaffold to {scaffold_path}: {e}")
        # Still return the scaffold even if save failed — agent can proceed
        saved_to = f"outputs/{name}/scaffold.json (save failed: {e})"

    # ── Return ─────────────────────────────────────────────────────────────────
    instruction = (
        f"Review this scaffold. Once approved, implement files one by one in the "
        f"order listed in implementation_order, saving each to outputs/{name}/. "
        f"After all files are written, run the test_command to verify the project "
        f"works. If it fails, read the error, fix the relevant file, and run again."
    )

    return {
        "success":    True,
        "scaffold":   scaffold,
        "saved_to":   saved_to,
        "file_count": file_count,
        "instruction": instruction,
    }


# ---------------------------------------------------------------------------
# Tool registration
# ---------------------------------------------------------------------------

def register_scaffold_tools() -> None:
    """Register scaffold_project with the live tool registry."""
    register_tool(
        name="scaffold_project",
        description=(
            "Generate a complete project specification before writing any code. "
            "Use this FIRST for any multi-file software project. Returns a structured "
            "plan: directory structure, file purposes, dependency order, entry point, "
            "test command, and implementation notes. Does NOT write source files — "
            "it produces the architecture plan for the agent to follow."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "name": {
                    "type":        "string",
                    "description": "Short project identifier used as directory name (e.g. 'todo_cli', 'weather_api').",
                },
                "description": {
                    "type":        "string",
                    "description": "One-sentence description of what the project should do.",
                },
                "project_type": {
                    "type":        "string",
                    "description": "Project type: 'python', 'web', 'cli', 'library', or 'api'. Defaults to 'python'.",
                    "enum":        ["python", "web", "cli", "library", "api"],
                },
            },
            "required": ["name", "description"],
        },
        handler=scaffold_project,
        is_destructive=False,  # only writes internal scaffold.json, not user data
    )
    logger.info("[startup] Registered tool: scaffold_project")
